name             'hadoop_wrapper'
maintainer       'namabile'
maintainer_email 'amabile.n@gmail.com'
license          'All rights reserved'
description      'Wraps the hadoop cookbook'
long_description 'Wraps the hadoop cookbook'
version          '0.1.0'
