name             'fsharp'
maintainer       'namabile'
maintainer_email 'amabile.n@gmail.com'
license          'All rights reserved'
description      'Installs/Configures fsharp'
long_description 'Installs/Configures fsharp'
version          '0.1.0'
