name             'anaconda_wrapper'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures anaconda_wrapper'
long_description 'Installs/Configures anaconda_wrapper'
version          '0.1.0'
